// server/src/mockData.ts
import type { Country, UserProfile } from './types.js';

export const COUNTRIES: Country[] = [
    { id: 'AF', name: 'Afganistán', locale: 'fa-AF' },
    { id: 'DE', name: 'Alemania', locale: 'de-DE' },
    { id: 'AG', name: 'Antigua y Barbuda', locale: 'en-AG' },
    { id: 'SA', name: 'Arabia Saudita', locale: 'ar-SA' },
    { id: 'DZ', name: 'Argelia', locale: 'ar-DZ' },
    { id: 'AR', name: 'Argentina', locale: 'es-AR' },
    { id: 'AT', name: 'Austria', locale: 'de-AT' },
    { id: 'AU', name: 'Australia', locale: 'en-AU' },
    { id: 'BS', name: 'Bahamas', locale: 'en-BS' },
    { id: 'BD', name: 'Bangladesh', locale: 'bn-BD' },
    { id: 'BB', name: 'Barbados', locale: 'en-BB' },
    { id: 'BE', name: 'Bélgica', locale: 'fr-BE' },
    { id: 'BZ', name: 'Belice', locale: 'en-BZ' },
    { id: 'BO', name: 'Bolivia', locale: 'es-BO' },
    { id: 'BR', name: 'Brasil', locale: 'pt-BR' },
    { id: 'BG', name: 'Bulgaria', locale: 'bg-BG' },
    { id: 'KH', name: 'Camboya', locale: 'km-KH' },
    { id: 'CA', name: 'Canadá', locale: 'en-CA' },
    { id: 'QA', name: 'Catar', locale: 'ar-QA' },
    { id: 'CL', name: 'Chile', locale: 'es-CL' },
    { id: 'CN', name: 'China', locale: 'zh-CN' },
    { id: 'CO', name: 'Colombia', locale: 'es-CO' },
    { id: 'KR', name: 'Corea del Sur', locale: 'ko-KR' },
    { id: 'CR', name: 'Costa Rica', locale: 'es-CR' },
    { id: 'CU', name: 'Cuba', locale: 'es-CU' },
    { id: 'DK', name: 'Dinamarca', locale: 'da-DK' },
    { id: 'DM', name: 'Dominica', locale: 'en-DM' },
    { id: 'EC', name: 'Ecuador', locale: 'es-EC' },
    { id: 'EG', name: 'Egipto', locale: 'ar-EG' },
    { id: 'SV', name: 'El Salvador', locale: 'es-SV' },
    { id: 'AE', name: 'Emiratos Árabes Unidos', locale: 'ar-AE' },
    { id: 'SK', name: 'Eslovaquia', locale: 'sk-SK' },
    { id: 'ES', name: 'España', locale: 'es-ES' },
    { id: 'US', name: 'Estados Unidos', locale: 'en-US' },
    { id: 'PH', name: 'Filipinas', locale: 'en-PH' },
    { id: 'FI', name: 'Finlandia', locale: 'fi-FI' },
    { id: 'FJ', name: 'Fiyi', locale: 'en-FJ' },
    { id: 'FR', name: 'Francia', locale: 'fr-FR' },
    { id: 'GR', name: 'Grecia', locale: 'el-GR' },
    { id: 'GD', name: 'Granada', locale: 'en-GD' },
    { id: 'GT', name: 'Guatemala', locale: 'es-GT' },
    { id: 'HK', name: 'Hong Kong', locale: 'zh-HK' },
    { id: 'HN', name: 'Honduras', locale: 'es-HN' },
    { id: 'HU', name: 'Hungría', locale: 'hu-HU' },
    { id: 'IN', name: 'India', locale: 'en-IN' },
    { id: 'ID', name: 'Indonesia', locale: 'id-ID' },
    { id: 'IQ', name: 'Irak', locale: 'ar-IQ' },
    { id: 'IR', name: 'Irán', locale: 'fa-IR' },
    { id: 'IL', name: 'Israel', locale: 'he-IL' },
    { id: 'IT', name: 'Italia', locale: 'it-IT' },
    { id: 'JM', name: 'Jamaica', locale: 'en-JM' },
    { id: 'JP', name: 'Japón', locale: 'ja-JP' },
    { id: 'JO', name: 'Jordania', locale: 'ar-JO' },
    { id: 'KZ', name: 'Kazajstán', locale: 'kk-KZ' },
    { id: 'KE', name: 'Kenia', locale: 'en-KE' },
    { id: 'KW', name: 'Kuwait', locale: 'ar-KW' },
    { id: 'LA', name: 'Laos', locale: 'lo-LA' },
    { id: 'LB', name: 'Líbano', locale: 'ar-LB' },
    { id: 'MO', name: 'Macao', locale: 'zh-MO' },
    { id: 'MY', name: 'Malasia', locale: 'ms-MY' },
    { id: 'MA', name: 'Marruecos', locale: 'ar-MA' },
    { id: 'MX', name: 'México', locale: 'es-MX' },
    { id: 'MM', name: 'Myanmar', locale: 'my-MM' },
    { id: 'NP', name: 'Nepal', locale: 'ne-NP' },
    { id: 'NI', name: 'Nicaragua', locale: 'es-NI' },
    { id: 'NG', name: 'Nigeria', locale: 'en-NG' },
    { id: 'NO', name: 'Noruega', locale: 'nb-NO' },
    { id: 'NZ', name: 'Nueva Zelanda', locale: 'en-NZ' },
    { id: 'OM', name: 'Omán', locale: 'ar-OM' },
    { id: 'NL', name: 'Países Bajos', locale: 'nl-NL' },
    { id: 'PK', name: 'Pakistán', locale: 'en-PK' },
    { id: 'PA', name: 'Panamá', locale: 'es-PA' },
    { id: 'PG', name: 'Papúa Nueva Guinea', locale: 'en-PG' },
    { id: 'PY', name: 'Paraguay', locale: 'es-PY' },
    { id: 'PE', name: 'Perú', locale: 'es-PE' },
    { id: 'PL', name: 'Polonia', locale: 'pl-PL' },
    { id: 'PT', name: 'Portugal', locale: 'pt-PT' },
    { id: 'CZ', name: 'República Checa', locale: 'cs-CZ' },
    { id: 'DO', name: 'República Dominicana', locale: 'es-DO' },
    { id: 'GB', name: 'Reino Unido', locale: 'en-GB' },
    { id: 'RO', name: 'Rumania', locale: 'ro-RO' },
    { id: 'RU', name: 'Rusia', locale: 'ru-RU' },
    { id: 'KN', name: 'San Cristóbal y Nieves', locale: 'en-KN' },
    { id: 'VC', name: 'San Vicente y las Granadinas', locale: 'en-VC' },
    { id: 'LC', name: 'Santa Lucía', locale: 'en-LC' },
    { id: 'SE', name: 'Suecia', locale: 'sv-SE' },
    { id: 'CH', name: 'Suiza', locale: 'de-CH' },
    { id: 'TH', name: 'Tailandia', locale: 'th-TH' },
    { id: 'TW', name: 'Taiwán', locale: 'zh-TW' },
    { id: 'TN', name: 'Túnez', locale: 'ar-TN' },
    { id: 'TR', name: 'Turquía', locale: 'tr-TR' },
    { id: 'TT', name: 'Trinidad y Tobago', locale: 'en-TT' },
    { id: 'UA', name: 'Ucrania', locale: 'uk-UA' },
    { id: 'UY', name: 'Uruguay', locale: 'es-UY' },
    { id: 'VE', name: 'Venezuela', locale: 'es-VE' },
    { id: 'VN', name: 'Vietnam', locale: 'vi-VN' },
    { id: 'ZA', name: 'Sudáfrica', locale: 'en-ZA' },
    { id: 'SG', name: 'Singapur', locale: 'en-SG' },
    { id: 'SY', name: 'Siria', locale: 'ar-SY' },
    { id: 'LK', name: 'Sri Lanka', locale: 'en-LK' },
];

// Simulamos una "Base de datos" de usuarios basada en el token que llega por URL
// Token '123' = Usuario con datos (Happy path de recarga de datos)
// Token 'new' = Usuario nuevo (Formulario vacío)
export const USERS_DB: Record<string, UserProfile> = {
    '123': {
        fullname: 'Juan Pérez',
        address: 'Calle Falsa 123, Piso 4',
        countryId: 'AR'
    },
    '456': {
        fullname: 'João Silva',
        address: 'Av. Paulista 1000',
        countryId: 'BR'
    }
};